example: example.c single.c single.h
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow -o example example.c -lcs50 -lm single.c
#objetivo: dependencias
#	instrucciones (con el espacio del principio "\t")